### ISSUE TITLE
Should vehicle number plates be blurred?

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#145]
Some photos contain clearly readable vehicle plates. E.g. https://openbenches.org/bench/4491. OpenBenches contains a public record that will exist indefinitely of exactly where that car was at 10:03 on 2018-02-24 without consent of the car's owner (assuming it doesn't belong to the uploader). Are visible plates OK legally, regardless of where in the world a photo was taken, whether the vehicle is on private or public land, whether the photographer was standing on public or private land? Is it OK, I'm not sure what the word is, ethically? If OpenBenches was contacted by someone objecting to visibility of a vehicle plate in a photo, what would your response be?

Obviously if you park your vehicle anywhere in public anyone who happens to be in the same place at the same time can see it. But there's a difference between that and there being a photo on the Internet forever which shows your vehicle, clearly identifiable, with date, time, latitude, longitude.

The Interweb has lots of people's opinions on whether visible plates are OK legally, but I can't find anything substantive. I'm thinking there's probably a reason Google went to the surely quite considerable effort of blurring out plates in Street View other than they thought it would be a nice thing to do.

Out of curiosity I fed the photo with the number plate visible from bench 4491 to https://github.com/openalpr/openalpr It found nothing. I fed it cropped version of the photo that contained little more than the car and it identified most of the plate. (It's not obvious, but the -j option causes output to include coordinates.)

**Comment by edent** [comment]
We spent some time discussing this at the UKGovCamp Unconference.  It boils down to two things.

Firstly, from https://publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/27305.htm

>  17.  There is now a two-stage test for determining cases where an infringement of the right to privacy is alleged—
> (1)  The court must decide whether the information is in principle protected by article 8 in that the claimant has a "reasonable expectation of privacy" in respect of the information. If that is not so then the claimant's case fails.
> (2)  If there is a reasonable expectation of privacy, the court balances the article 8 rights of the claimant against the defendant's article 10 rights.

Photos taken in public fail the "reasonable expectation of privacy" test.  Even if they didn't, the photographer has the right to freedom of expression.

Secondly, if someone is distressed by a photo, we'd look at whether it was reasonable to remove it. For example, if someone genuinely didn't want their parents' bench on the site, we could remove it.  Or, if they could satisfactorily prove their car was in an image and it was causing a problem, it could be edited out.

Google, I suspect, were over-cautious because they were building such a huge data-set.  I don't see it being a problem for our small site. Flickr, to pick another example, doesn't blur out number-plate, faces, or other things like that.

Thankfully, there have been no concerns yet with what we're doing. We'll cross that bridge when we come to it.

(Leaving open for further discussion.)

**Comment by edent** [comment]
Added some points to https://www.openbenches.org/blog/privacy/
