### ISSUE TITLE
Remove log in requirement

### ISSUE THREAD

**Issue by edent** [edent/openbenches#20]
A complaint from @symroe ;-)

https://twitter.com/symroe/status/886515656094617600

As a user, I don't want to have to log in via Twitter - because that adds friction.

**Comment by edent** [comment]
* Remove login requirement
* Store IP address & timestamp
* Leave benches off the main map until manually approved?

**Comment by symroe** [comment]
Complaint is strong :) My point was that this is an app where you want many people to use a few times ever vs something you want to use daily and form a community around. I want to be able to snap a bench as soon as I see one, not worry about logging in. (I should note that I don't use the official Twitter app on my phone and I have 2FA on my Twitter account – this means authing with Twitter is quite involved!)

As I said later, it's a trade-off between that and all the benefits you get from logging in (community, lack of abuse etc). My anecdote is that https://electionleaflets.org (that I run currently) doesn't ask for log in at the point of upload and hasn't had abuse (yet).

On pre-moderation, I've been warned off that (with nuance and caveats) by @francisdavey. I expect this is less controversial than most cases where pre-moderation is considered.

It's an interesting trade-off, and I'm happy to be told to just log in already :)

**Comment by francisdavey** [comment]
Pre-moderation has the downside that you are more responsible for what then gets posted. You can't simply say "we didn't see it". On the other hand the law has shown some generosity to people who do pre-moderate (because it is usually a good thing). Things may of course change with the current political atmosphere.

But if this is about taking photographs of benches, it is hard to see what sort of liability that might arise. I could of course be wrong, but it would be odd for a genuine picture of a bench to be defamatory (say).

If there were an infringement of copyright, that would be unlikely to be picked up in pre-moderation.

Anyway, I am thinking out loud here - I am very much not openbenches lawyer :-).

**Comment by edent** [comment]
The reason for moderation was more to stop spam or offensive non-bench content being published. Will try it without moderation and see what happens.
